### ISSUE TITLE
没有下理base选项

### ISSUE THREAD

**Issue by cnickd** [TabSpace/gulp-qcloud-cos-upload#1]
在上传时设就算设置了gulp.src([....],{base:'dir'})仍然无效，发现代码里没有处理base，也不知道算不算BUG

**Comment by TabSpace** [comment]
感谢提交提案。
上传参数中，prefix 指定了上传目标路径，我担心引入base会导致这里理解混乱。
不过考虑到这个选项默认可以不设置，我回头会加上，以增加使用灵活性。
base 路径会附加到 prefix 之后，连接后形成完整线上路径。

**Comment by TabSpace** [comment]
功能已实现。
